### PR TITLE
Implement unit testing environment

### PR DESCRIPTION
**Pull request by alexanderschnitzler**
This set of patches implements a unit testing environment and one additional test to test the generation of the require section of TYPO3 extensions.

Additionally the build process has been moved away from the class context.

### CODE REVIEW

**Comment by tmaroschik** [comment]
I like that change, but I have to check first what effect the path change will have.

**Comment by lars85** [comment]
thanks Alexander! :+1:

**Comment by tmaroschik** [comment]
Thanks for this one. We need to change the entry point to Build.sh

@fabarea , I have just read rights on the server. Can you update and tell cron to execute Build.sh instead of the current php script?

**Comment by lars85** [comment]
composer.typo3.org is connected to git://git.typo3.org/Sites/ComposerTypo3Org.git... @tmaroschik, I have root access on the server - but I don't when then sync between git.typo3.org and github.com is running.

**Comment by fabarea** [comment]
Looking at the issue. What seems a bit weird is the sh script ``Build.sh`` invoking ``#! /usr/bin/env php`` at the top. Either it is a "sh" script or a "php".

Also running /var/www/vhosts/composer.typo3.org/deploy/current/Build.sh, raises 

    PHP Fatal error:  Class 'PackagesTYPO3ExtensionsGenerator' not found in /var/www/vhosts/composer.typo3.org/deploy/current/Build.sh on line 6

But how shall we continue? The Cron task must be changed by Chef, I can take care of that after we fix the fatal.

**Comment by alexanderschnitzler** [comment]
That's weird because I tested it locally and it worked pretty well. Are you sure you ran `composer install` again? As I changed the autoloading to class maps it might be that the new autoloading information isn't yet known to the composer autoloader.

Maybe run `composer clearcache` and `composer dumpautoload` to be really sure, that the class map is created correctly.

Regarding the script name I don't  see any issues with that but we can also make it a php file or do not use any file extension at all.

**Comment by fabarea** [comment]
``composer install`` was the missing step. Cron job script has been updated as well to be ``Build.sh``. So wonderland!

**Pull request merged**
